### ISSUE TITLE
Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.Error: NotFoundError: A requested file or directory could not be found at the time an operation was processed.    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Gh053d413x** [bridge-core/editor#850] opened 2023-01-08 00:19 UTC
**Summary**
So, I've been trying to import default pack templates and pops up with a NotFoundError.

**To Reproduce**
Here are the steps to reproduce the error:

1. Drag the default pack you want to import into the editor
2. Let go of left click to 'import' the default pack

**Observed behavior**
I did step 1 and two in that order and got the error.

**Expected behavior**
When I do step 1 and 2, it is supposed to import the pack as a vanilla default pack.

**Screenshots / File Attachments**
[problem.zip](https://github.com/bridge-core/editor/files/10367425/problem.zip)
This is the screenshots of the problem in this folder

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: 2.6.0

**Comment by pascal541** [comment] 2023-02-20 18:31
Duplicate of #852

**Closed by pascal541** 2023-02-20 18:31 UTC
Labels: bug
