### ISSUE TITLE
Too many notifications from unhandled browser errors

### ISSUE THREAD

**Issue by jasonjgardner** [bridge-core/editor#236] opened 2021-11-18 23:54 UTC
**Summary**
[Creating sidebar notifications for unhandled errors](https://github.com/bridge-core/editor/blob/5aeeb1217dc1fb3d58f251dbc1c4ccb30c24f208/src/components/Notifications/Errors.ts#L51) can result in too many notification icons in the sidebar. Notifications are being created for browser errors not caused by bridge.

**To Reproduce**
1. Open bridge. with Vue Devtools enabled
2. Allow bridge. file system access
3. Select a component to inspect. (Any component)

**Observed behavior**
A `TypeError` is unhandled and `components/Notifications/Errors.ts` creates endless sidebar notifications.

Browser console repeatedly outputs:
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Symbol.toPrimitive)')
> at comlink.ts:297

**Expected behavior**
Ideally, there would be no conflicts with Vue Devtools. I realize this particular issue might not be caused by bridge. itself, but in any case, there should be a limit to the number of sidebar notifications created.

The callback function for `window.onunhandledrejection` should filter which `PromiseRejectionEvent`s are reported in bridge.'s sidebar, otherwise bridge. may report errors caused by whatever else might have access to the `window` scope (browser extension, content scripts, etc.).

The [`SidebarState` interface](https://github.com/bridge-core/editor/blob/main/src/components/Sidebar/state.ts#L10) could potentially set a limit on the length of its `sidebarElements` and/or debounce creating notifications.

(Figuring out what is causing this conflict with bridge., Devtools, and comlink could be good too.)

**Screenshots / File Attachments**
![Notifications and dev tools output](https://user-images.githubusercontent.com/1903667/142498136-2e2e9027-4eba-4165-914a-f315b13d6fe2.png)
![bridge. Error window](https://user-images.githubusercontent.com/1903667/142503840-fefe0e9e-7449-4573-a27d-5775b49009b7.png)

**Platform:**
 - Windows 10
 - Edge 95

**Comment by solvedDev** [comment] 2021-11-20 12:47
The problem is that Vue dev tools sends messages that comlink tries to decode unsuccessfully. I don't think we can fix this atm; I am therefore closing this issue in favor of #158

**Closed by solvedDev** 2021-11-20 12:47 UTC
Labels: bug
