### ISSUE TITLE
Error: Error: Failed to access "C:\Users\11654\AppData\Local\com.bridge.dev\bridge\extensions\MinecraftDocumentationImplementation\Docs": Directory does not existError: Error: Failed to access "C:\Users\11654\AppData\Local\com.bridge.dev\bridge\extensions\MinecraftDocumentationImplementation\Docs": Directory does not exist    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by Mchandless** [bridge-core/editor#859] opened 2023-01-22 08:09 UTC
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachmenn to '....'
4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable,ts**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by ThomasOrs** [comment] 2023-01-22 10:58
@Mchandless please fill out the sections in the bug report to help it get solved.

**Comment by ThomasOrs** [comment] 2023-01-22 11:01
Duplicate of #849

**Closed** 2023-01-22 19:22 UTC
Labels: bug, duplicate
