### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'IDENTIFIER')Error: TypeError: Cannot read properties of undefined (reading 'IDENTIFIER')    at window.onunhandledrejection (https://tauri.localhost/assets/main-5acbd52f.js:28:2506)

### ISSUE THREAD

**Issue by githumtime12323523464576** [bridge-core/editor#870] opened 2023-02-01 03:25 UTC
#**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by solvedDev** [comment] 2023-02-01 13:16
We need more information. Which preset did you use?

**Comment by outercloudstudio** [comment] 2023-04-19 00:25
Duplicate of #865

**Closed by outercloudstudio** 2023-04-19 00:25 UTC
Labels: bug, cannot reproduce
