### ISSUE TITLE
Saving does not always finish

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#403] opened 2022-04-03 17:52 UTC
**Summary**
Seemingly randomly, when saving a file, it will attempt to save (shown by the "loading" dialog box). However, the file will not end up saving. The unsaved icon in the file tab will be present, and no "compiling project" button will appear in the sidebar. The file is not updated in the synced `com.mojang` folder. Because of the "loading" dialog box that does not go away, bridge. is softlocked and must be refreshed.

**Observed behavior**
Current file fails to save and bridge. softlocks
**Expected behavior**
Current file should not fail to save.

**Platform (please complete the following information):**

-   OS: Windows 10
-   App Version: 2.2.6

**Comment by solvedDev** [comment] 2022-04-25 12:30
Does this happen for both the tree & text editor?

**Comment by Chikorita-Lover** [comment] 2022-04-25 12:32
I haven't had this issue recently, so it might've been fixed. I was using the text editor while I did get the issue.

**Comment by solvedDev** [comment] 2022-04-25 12:33
Closing as cannot reproduce then, feel free to reopen if necessary

**Comment by Chikorita-Lover** [comment] 2022-04-30 02:59
This just happened to me again, still with no console errors.

**Comment by solvedDev** [comment] 2022-06-26 17:04
I think I found the cause of this issue: Our document formatter sometimes doesn't run correctly (for some weird reason). 
I've already pushed a change to the nightly build that removes the loading window that pops up upon saving files (there's now a nice loading indicator within the tab bar) and I am now working on aborting the format document request after a second in case it fails

**Closed** 2022-06-26 17:44 UTC
Labels: bug, cannot reproduce
