### ISSUE TITLE
 Custom Keybinds

### ISSUE THREAD

**Issue by Eko-byte** [bridge-core/editor#295] opened 2022-01-10 02:24 UTC
**Summary**
Currently in Bridge v2 there are keybinds and shortcuts to do certain actions, the ability for us being able to set say refresh to shift R for example instead of ctrl alt r.

**Alternatives/Considerations**
An alternative to this could be to change a few of the current keybinds to standard keybinds such as ctrl shift r for refreshing.

**Additional context/Motivation**
The main reason this would be useful is because certain current keybinds can overlap with other keybinds on the computer such as nividia overlay when activating refresh, also people with less keys could probably benefit from this

**Comment by solvedDev** [comment] 2022-01-10 13:02
I was pretty sure we already had an issue for this feature request but that's apparently not the case 🙃

**Comment by solvedDev** [comment] 2022-07-29 13:09
Nvm, this is a duplicate of #159

**Closed by solvedDev** 2022-07-29 13:09 UTC
Labels: duplicate, feature
