### ISSUE TITLE
Tree editor: "else" not supported when "if" is in a "$ref"

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#358] opened 2022-02-08 07:27 UTC
https://github.com/bridge-core/editor-packages/blob/main/packages/minecraftBedrock/schema/block/main.json#L76-L84

In block files, auto-completions break when "holidayCreatorFeatures" is disabled
Also occurs in item files and potentially more

**Comment by solvedDev** [comment] 2022-02-18 12:59
Duplicate of #301

**Closed by solvedDev** 2022-02-18 12:59 UTC
Labels: bug, duplicate
