### ISSUE TITLE
Open Files Not saving to project

### ISSUE THREAD

**Issue by RealJoshMC** [bridge-core/editor#318] opened 2022-01-18 20:36 UTC
https://user-images.githubusercontent.com/87614711/150014160-cddb6491-64ee-497a-99df-f9ecbefc0fea.mp4

```
i open my animation and save it to my project but its not showing on my project (RP)

im not sure about the other files
```

**Comment by solvedDev** [comment] 2022-01-18 21:11
Duplicate of #316

**Closed** 2022-01-18 21:11 UTC
Labels: bug, duplicate
