### ISSUE TITLE
Compiler get stuck and pops this error

### ISSUE THREAD

**Issue by ExDrill** [bridge-core/editor#227] opened 2021-11-10 15:12 UTC
**Summary**
Compiling in any sort of way, either from restarting dev server, re-syncing com.mojang or using the compiler normally will just get stuck and I would have to keep closing out and compiling for it to make some progress.

**To Reproduce**
I'm not really sure how this is reproduced, this just seems like something random since it's started happening out of nowhere.

**Observed behavior**
It gets stuck at certain percentages. If bridge is restarted and you use the compiler again, it can make some progress.

**Expected behavior**
It should not be stuck, it should simply finish the compiling task.

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/72329798/141139022-e325007d-e6c7-4162-89b2-f7317565303f.png)

**Platform (please complete the following information):**
 Windows 10, Chrome 95

**Comment by ExDrill** [comment] 2021-11-10 15:14
Okay it just gets stuck at random percentages.

**Comment by solvedDev** [comment] 2021-11-13 14:54
This is a duplicate of #85. Could you please add a screenshot of your project config (specifically the compiler plugins you have installed) to this issue?

**Closed by solvedDev** 2021-11-13 14:54 UTC
Labels: bug, duplicate
