### ISSUE TITLE
com.mojang project loading not working

### ISSUE THREAD

**Issue by imsolucid** [bridge-core/editor#602] opened 2022-09-04 15:33 UTC
**Summary**
Bridge v2 doesnt locate existing packs that are in the com.mojang folders

**To Reproduce**
follow the steps to complete setup/ when "installing" bridge.

**Observed behavior**
doesnt locate existing packs that are in the com.mojang folders 
like
development_x_packs

**Expected behavior**
supposed to locate the packs from those folders

**Platform (please complete the following information):**

-   OS: windows 10
-   App Version: 2.3.2

**Comment by solvedDev** [comment] 2022-09-08 11:53
Closing the issue as cannot reproduce for now as the feature is working fine for me and you did not reply with further information

**Closed by solvedDev** 2022-09-08 11:53 UTC
Labels: bug, cannot reproduce
