### ISSUE TITLE
An Object is being added when add custom Value in Tree Editor

### ISSUE THREAD

**Issue by a86296007** [bridge-core/editor#323] opened 2022-01-20 04:48 UTC
**Summary**
An Object is being added when using add Value

**To Reproduce**

1. Open a .json file with the **Tree Editor** mode. 
2. Select a object should have **value** added. (for example: "minecraft:type_family" -> "family" )
3. Add a custom value and **press enter**.  (**not selecting auto-completed options**)
4. Observe result. 

**Observed behavior**
An Object was added instead of a value. 
**Expected behavior**
A value was added below. 

**Screenshots / File Attachments**
https://user-images.githubusercontent.com/91132489/150275382-68682e04-d74e-4c0c-a8cc-271be8b96738.mp4

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: V2.2.1

**Comment by solvedDev** [comment] 2022-01-20 08:05
Duplicate of #317

**Closed** 2022-01-20 08:05 UTC
Labels: bug, duplicate
