### ISSUE TITLE
I can not make a block

### ISSUE THREAD

**Issue by cjibo** [bridge-core/editor#44] opened 2021-07-29 17:54 UTC
I am trying to make a block with the bridge v2 and it will not work

**Comment by FrederoxGit** [comment] 2021-07-29 17:56
Could you provide some more details? Is this block not being created inside of bridge? Or does it not work in game?

**Comment by cjibo2** [comment] 2021-07-29 18:07
hi other account is bugged so yah not being created inside of bridge

**Comment by cjibo2** [comment] 2021-07-29 18:09
this is my other account because my main is glitchy.

**Comment by cjibo2** [comment] 2021-07-29 18:10
> Could you provide some more details? Is this block not being created inside of bridge? Or does it not work in game?


not being created inside of bridge

**Comment by cjibo2** [comment] 2021-07-29 18:11
hello?

**Comment by solvedDev** [comment] 2021-07-29 20:17
duplicate of #45

**Closed by solvedDev** 2021-07-29 20:17 UTC
Labels: bug, duplicate
