### ISSUE TITLE
Possibility to install an extension locally and globally

### ISSUE THREAD

**Issue by Tschipp** [bridge-core/editor#315] opened 2022-01-17 09:15 UTC
**Summary**
Sometimes it is useful to be able to additionally install an extension locally, even if it is already globally installed. This is so that the whole team that's working on a project has the same extensions.

**Alternatives/Considerations**
Only alternative right now is uninstalling the global extension and reinstalling it locally.

**Comment by solvedDev** [comment] 2022-01-17 11:44
Turns out this is a duplicate of #56

**Closed by solvedDev** 2022-01-17 11:44 UTC
Labels: duplicate, feature

**Comment by Tschipp** [comment] 2022-01-17 12:32
Oh wow 🤦 Even made by me lol
