### ISSUE TITLE
Mobile: Error when importing project

### ISSUE THREAD

**Issue by Joelant05** [bridge-core/editor#486] opened 2022-06-28 16:59 UTC
Project is not defined errors show when importing attached project (as a .mcaddon)

https://discord.com/channels/602097536404160523/859382440874213376/99106731710863365

[smartphone_addon_v2_1.mcaddon.zip](https://github.com/bridge-core/editor/files/9003166/smartphone_addon_v2_1.mcaddon.zip)

**Comment by solvedDev** [comment] 2022-07-20 09:19
I cannot reproduce the issue. Maybe it has been fixed by our changes on v2.3 already

**Closed by solvedDev** 2022-07-20 09:19 UTC
Labels: bug, cannot reproduce
