### ISSUE TITLE
Extension gui error

### ISSUE THREAD

**Issue by NguyenDuck** [bridge-core/editor#632] opened 2022-10-06 01:23 UTC
**Summary**
Mirror bug, i'm not sure it's cause on other client!
It's just on my client?
Idk!

**To Reproduce**

 - Go to 'Extension'
 - Click on 'Installed'
 - Click on any tag below the extension name
 - Click on close or search bar or any except share
 - Observe result

**Observed behavior**
Belike not response, but click share is available
**Expected behavior**
Working correctly

**Screenshots / File Attachments**
![image](https://user-images.githubusercontent.com/83252725/194192433-f495f1d0-5cb3-492f-adf9-ccf197607e9a.png)

**Platform (please complete the following information):**

-   OS: Windows 11
-   App Version: 2.3.3

**Comment by solvedDev** [comment] 2022-10-11 21:45
Can you maybe share a short video of your problem?

**Comment by NguyenDuck** [comment] 2022-10-12 08:27
> Can you maybe share a short video of your problem?

https://youtu.be/Nl4KCJHu_7A

**Comment by solvedDev** [comment] 2022-10-12 08:56
Thanks!
I still cannot reproduce the issue though. 
1) Can you confirm that it also occurs on the nightly build? (https://nightly.bridge-core.app/)
2) Does this happen within all of your projects? If it only happens in a single project, can you share the .brproject file with me?

**Comment by NguyenDuck** [comment] 2022-10-13 01:20
> Thanks! I still cannot reproduce the issue though.
> 
> 1. Can you confirm that it also occurs on the nightly build? (https://nightly.bridge-core.app/)
> 2. Does this happen within all of your projects? If it only happens in a single project, can you share the .brproject file with me?

It's good work on Nightly build
Here is file https://www.mediafire.com/file/3u32r8a0e7f0t4c/Exnihilo+Bedrock.brproject/file

**Comment by solvedDev** [comment] 2022-10-13 07:29
Thank you! Closing the issue since it is fixed on the nightly build 👍

**Closed** 2022-10-13 07:29 UTC
Labels: bug, cannot reproduce
